url: ""
baseurl: "/gba-fwa"

title: "Blockchain Transparency Playbook"

plugins:
  - jekyll-sitemap
  - jekyll-datapage-generator

page_gen:
  - data: "use_cases"
    template: "use_case"
    name: "slug"
    dir: "use-cases"

exclude:
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
  - node_modules
  - Gemfile
  - Gemfile.lock
